spring:
  application:
    name: mcp-client-demo
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus
    ollama:
      base-url: http://ollama.local:11434
      chat:
          options:
              model: llama3.2:1b
    openai:
      api-key: ${AI_OPENAI_API_KEY}
      base-url: ${AI_OPENAI_BASE_URL}
      chat:
        options:
          model: o4-mini-2025-04-16
    mcp:
      client:
        enabled: true
        name: ${spring.application.name}
        version: 1.0.0
        initialized: true
        request-timeout: 20s
        type: sync
        root-change-notification: true
        toolcallback:
          enabled: true
        sse:
          connections:
            # a list of McpSyncClient
            server1:
              url: http://localhost:9090
              sse-endpoint: /api/v1/sse
    chat:
      memory:
        repository:
          jdbc:
            mysql:
              jdbc-url: jdbc:mysql://localhost:3306/spring_ai_alibaba_mysql?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
              username: root
              password: root
              driver-class-name: com.mysql.cj.jdbc.Driver
              enabled: true

  logging.level:
    io.modelcontextprotocol: TRACE
    org.springframework.ai.mcp: TRACE